all: defense practice

defense: main.cpp menu.cpp location.cpp
	g++ -std=c++11 -o defense main.cpp menu.cpp location.cpp -I.

practice: practice.cpp
	g++ -std=c++11 -o practice practice.cpp -I.

clean:
	rm defense practice
